# https://kubernetes.io/docs/concepts/configuration/secret/
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: keycloak
type: Opaque
data:
  KEYCLOAK_PASSWORD: bXkta2V5Y2xvYWstcGFzc3dvcmQ=
  KEYCLOAK_MGMT_PASSWORD: bXkta2V5Y2xvYWstcGFzc3dvcmQ=
  POSTGRES_PASSWORD: XktcG9zdGdyZXMtcGFzc3dvcmQ=
